### ISSUE TITLE
eslint should look whether the client supports dynamicRegistration

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-eslint#16]
This is a lang server issue but I'll post the issue here for bookkeeping.

eslint should check the text editor's capabilities to see if it supports dynamicRegistration. If it doesn't, then it should not do the client/registerCapability request.

Alternatively, eslint should handle errors returned from requests.

**Comment by rchl** [comment]
I've created PR to [remove one](https://github.com/microsoft/vscode-eslint/pull/920) of them at least but no response so far.

The other one can also be probably removed but wanted to handle that in separate RP.

**Comment by rchl** [comment]
Actually, I think my PR was proved invalid.

This makes me think SublimeLSP is not handling it correctly.
`didChangeWorkspaceFolders` notification should only be sent when the server announces support for it statically using `workspace.workspaceFolders.changeNotifications` or it dynamically registers it.
We are currently sending that notification based on `workspace.workspaceFolders.supported` server capability.

But since we don't have dynamic registration feature currently, it's probably better to keep it that way.

**Comment by rchl** [comment]
> This is a lang server issue but I'll post the issue here for bookkeeping.
> 
> eslint should check the text editor's capabilities to see if it supports dynamicRegistration. If it doesn't, then it should not do the client/registerCapability request.
> 
> Alternatively, eslint should handle errors returned from requests.

Now, how would it do that for the case of `didChangeWorkspaceFolders` notification?
There is no related client capability with `dynamicRegistration` property. There is only `workspace.workspaceFolders` which is a boolean.

**Comment by rwols** [comment]
This is fixed by https://github.com/sublimelsp/LSP/pull/1005
