### ISSUE TITLE
Insert `CR` false positives on file with CRLF line endings

### ISSUE THREAD

**Issue by jakubmazanec** [sublimelsp/LSP-eslint#40]
Hello,
LSP-eslint is reporting false positives when the file has CRLF; I have Prettier ESLint plugin and there is an error/suggestion to insert CR at the end of a line, even when it's not necessary (also, autofix on save messes up the file, inserting the unneeded CR). Here is repo where I can reproduce the issue: https://github.com/jakubmazanec/lsp-eslint-crlf-issue (it also contains a screenshot of the issue).
Can somebody help me investigate this? Thanks.

**Comment by rchl** [comment]
I believe this is due to ST normalizing line endings to LF always. So that's what the server ends up "seeing".

I think the only solution to that is to disable the rule that checks line endings. Or just switch your files to use LF line-endings which is generally a good idea for better cross-platform portability.

(In the new LSP spec version (3.16.0) there was a `normalizesLineEndings` client capability added but I don't see how it would help here since the server still won't know what's the actual line ending on the line)

**Comment by jakubmazanec** [comment]
And is there a possibility how can I add some custom override of these linter rules in Sublime settings? I can't modify ESLint configs in all repos I'm working on just because I'm having these issues.

**Comment by rchl** [comment]
I think you might be able to override eslint rules with a eslint configuration file places above your project's directory (as long as your project doesn't specify `root: true`). Check https://eslint.org/docs/user-guide/configuring#using-configuration-files-1 for more info.

**Comment by jakubmazanec** [comment]
Unfortunately, that's not universal, and again - I can't modify every repo just because of my problems with Sublime. But thanks for the help and quick responses.

I'm closing this issue, but I still think there should be some kind of option to disable LSP-eslint checking and reporting anything that's got something to do with line endings. Not everyone can change whole codebase to LF (even if it would be better, I know :)).
